linux: &linux
   os: linux
   dist: bionic
   language: python
   sudo: required
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic

matrix:
   include:
      - <<: *linux
        env: CONAN_COMPILER=gcc CONAN_COMPILER_VERSION=4.8
      - <<: *osx
        osx_image: xcode8.3
      - <<: *osx
        osx_image: xcode9.4
      - <<: *osx
        osx_image: xcode10.3
      - <<: *osx
        osx_image: xcode11.2

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh